services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/api.Dockerfile
    container_name: integra-api
    restart: unless-stopped
    ports:
      - "3003:3001"
    environment:
      POSTGRES_HOST: db-qgv5lrlyqgzhmpmxkccokx6b
      POSTGRES_PORT: 5432
      POSTGRES_DB: integra_contexto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: coolify-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: XBwH+0AY1knXrJJ2Cz6FI10EWKIkguulXbHpjpDw2u8=
      API_PORT: "3001"
    networks:
      - coolify

  worker:
    build:
      context: .
      dockerfile: infrastructure/docker/worker.Dockerfile
    container_name: integra-worker
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db-qgv5lrlyqgzhmpmxkccokx6b
      POSTGRES_PORT: 5432
      POSTGRES_DB: integra_contexto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: coolify-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: XBwH+0AY1knXrJJ2Cz6FI10EWKIkguulXbHpjpDw2u8=
    networks:
      - coolify

  web:
    build:
      context: .
      dockerfile: infrastructure/docker/web.Dockerfile
    container_name: integra-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://api.dtxnet.top
      NEXT_PUBLIC_WS_URL: wss://ws.dtxnet.top
    depends_on:
      - api
    networks:
      - coolify

networks:
  coolify:
    external: true